// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcxFCTv3QLJL50rBU7bQ76jUyVuXvJrX0',
    appId: '1:276501101976:web:0dbb6b10e648d80a713fed',
    messagingSenderId: '276501101976',
    projectId: 'cerverus-pet-spa',
    authDomain: 'cerverus-pet-spa.firebaseapp.com',
    storageBucket: 'cerverus-pet-spa.firebasestorage.app',
    measurementId: 'G-Q9XV5NC5D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHakzfvGw3L_jk7PGpGAXzn5I8l4hIKco',
    appId: '1:276501101976:android:d8324cdd097bf1b3713fed',
    messagingSenderId: '276501101976',
    projectId: 'cerverus-pet-spa',
    storageBucket: 'cerverus-pet-spa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpJfVxY7OSlVLpAYW7I65xKDHkTdoqc6g',
    appId: '1:276501101976:ios:6b697295b71cd027713fed',
    messagingSenderId: '276501101976',
    projectId: 'cerverus-pet-spa',
    storageBucket: 'cerverus-pet-spa.firebasestorage.app',
    iosBundleId: 'com.example.cerberusPetSpa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpJfVxY7OSlVLpAYW7I65xKDHkTdoqc6g',
    appId: '1:276501101976:ios:6b697295b71cd027713fed',
    messagingSenderId: '276501101976',
    projectId: 'cerverus-pet-spa',
    storageBucket: 'cerverus-pet-spa.firebasestorage.app',
    iosBundleId: 'com.example.cerberusPetSpa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcxFCTv3QLJL50rBU7bQ76jUyVuXvJrX0',
    appId: '1:276501101976:web:26fa99667bf0c759713fed',
    messagingSenderId: '276501101976',
    projectId: 'cerverus-pet-spa',
    authDomain: 'cerverus-pet-spa.firebaseapp.com',
    storageBucket: 'cerverus-pet-spa.firebasestorage.app',
    measurementId: 'G-QMQ2R86Z92',
  );
}
